use_frameworks!

target 'GMYCategorys_Example' do
  pod 'GMYCategorys', :path => '../'

  target 'GMYCategorys_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
